version: '3'

services:
  app:
    container_name: 'autodl'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - 3000:3000
    restart: 'unless-stoped'
