services:
  app:
    container_name: 'autodlv5'
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
    ports:
      - 3000:3000
    restart: 'unless-stopped'
